platform :ios, '16.0'

# Share dependencies across all targets
abstract_target 'ITZLITShared' do
  source 'https://github.com/CocoaPods/Specs.git'
  use_frameworks!

  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'GoogleSignIn'
  pod 'GoogleAPIClientForREST/YouTube'
  pod 'libPhoneNumber-iOS'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Branch'
  pod 'SDWebImage'
  pod 'SwiftLoader'
  pod 'IQKeyboardManagerSwift'
  pod 'SQLite.swift', '~> 0.15'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'SimpleImageViewer', :git => 'https://github.com/teamSolutionAnalysts/SimpleImageViewer.git', :branch => 'podWith'
  pod 'Socket.IO-Client-Swift'

  target 'ITZLIT'
  target 'ITZLIT Dev'
  target 'ITZLIT Stage'
end
